name: KingOfTheHill
version: ${project.version}
main: me.openliven.kothplate.KothPlatePlugin
api-version: '1.20'
author: mio-openliven
depend:
  - Vault
commands:
  koth:
    description: Manage the King of the Hill capture point.
    usage: /koth <set|reload|info>
    aliases:
      - kothplate
permissions:
  koth.admin:
    description: Allows managing the KingOfTheHill capture point.
    default: op
