name: KingOfTheHill
version: ${project.version}
main: me.openliven.kothplate.KothPlatePlugin
api-version: '1.20'
author: mio-openliven
depend:
  - Vault
commands:
  koth:
    description: Manage the King of the Hill capture point.
    usage: /koth <set|reload|info>
    permission: koth.admin
    permission-message: '§c[§6КотХ§c] У вас нет прав на выполнение этой команды!'
    aliases:
      - kothplate
permissions:
  koth.admin:
    description: Allows managing the KingOfTheHill capture point.
    default: op
